project_id = "nhulnikqfphofqpnmdba"

[functions]
# No separate enabled key in newer CLI, it figures it out from directory

[functions.generate-upload-url]
verify_jwt = true

[functions.start-mastering-job]
verify_jwt = true

[functions.get-job-status]
verify_jwt = true

[functions.audio-proxy]
verify_jwt = false

[functions.delete-account]
verify_jwt = true
